---
- name: gather content views
  uri:
    url: "https://{{base_Sat_URL}}/katello/api/organizations/{{organization_id}}/content_views"
    method: GET
    user: "{{sat_username}}"
    password: "{{sat_password}}"
    force_basic_auth: yes
    validate_certs: no
    header:
      Content-Type: application/json
      Accept: :application/json, version2
    body: >
      {
      "page" : 1,
      "per_page" : 1000,
      "sort" : {}
      }

    status_code: 200
    body_format: json
  register: content_info

- name: set list of content views
  set_fact:
    content_view_list_temp: "{{content_info.json | json_query('results[*].name') | join('\n')}}"

- name: set list of content views
  set_fact:
    content_view_list: "{{content_view_list_temp | replace('\\n', '\n')}}"
