---
- name: get content_view_id
  uri:
    url: "https://{{base_Sat_URL}}/katello/api/content_views"
    method: GET
    user: "{{sat_username}}"
    password: "{{sat_password}}"
    force_basic_auth: yes
    validate_certs: no
    header:
      Content-Type: application/json
      Accept: :application/json, version2
    body: >
      {"name" : "{{content_view_name}}"}
    status_code: 200
    body_format: json
  register: content_info
  delegate_to: localhost
- name: set content_view_id
  set_fact:
    content_view_id: "{{content_info.json.results[0].id}}"
