---
- import_tasks: overview_list.yml
  when: "'overview' in list_type"
- import_tasks: kernel_list.yml
  when: "'kernel' in list_type"
- import_tasks: package_list.yml
  when: "'package' in list_type"
- import_tasks: errata_list.yml
  when: "'errata' in list_type"
- import_tasks: email_lists.yml
  when: email_list == "true"
