---
- name: Get security update information
  shell: yum list all kernel
  args:
    warn: false
  register: security_info
- name: Print security update informaton
  debug:
    var: security_info.stdout_lines
- name: copy kernel list to file
  blockinfile:
    marker: "## {{inventory_hostname}} : {mark} "
    marker_begin: "Begin security Info"
    marker_end: "End security Info"
    block: "{{ security_info.stdout }}"
    create: yes
    path: "/tmp/patch_analysis_{{email_addr}}.txt"
    state: present
    insertafter: EOF
  delegate_to: localhost
  connection: local
  when: email_list == "true"
